### ISSUE TITLE
Support for variables from: root

### ISSUE THREAD

**Issue by afuno** [rogden/tailwind-config-viewer#11]
I noticed that now there is a problem if variables were declared, for example, in ':root'. Is there any solution for this problem now?

<img width="300" alt="Снимок экрана 2020-08-28 в 00 31 06" src="https://user-images.githubusercontent.com/2853419/91497029-e10abc80-e8c5-11ea-9a69-b507a22dcdb1.png">

**Comment by rogden** [comment]
This is an interesting use case. The config viewer doesn't load your compiled CSS file so it wouldn't have access to your CSS variables by default. One possible solution: I could add support for overrides/customization of the config viewer from your Tailwind config file. Example:

```js
// in your tailwind.config.js file
module.exports = {
  theme: {
    // ... your theme config
  },
  configViewer: {
    cssColorVars: {
      'var(--color-black)': '#000000',
      'var(--color-white)': '#ffffff',
      // ...other colors vars
    }
  }
}
```

What do you think? Also, are you using CSS vars for theming? If so, this would only solve for your default/::root color vars.

**Comment by rogden** [comment]
@afuno I added the ability to replace values from your theme when used in the config viewer. This should solve your issue with the CSS variables. See: https://github.com/rogden/tailwind-config-viewer#themereplacements

**Comment by afuno** [comment]
@rogden Thanks. Everything is successful.

**Comment by kissu** [comment]
If we do have an `.scss` file containing
```scss
:root {
  --color-dark-500: hsl(0, 0%, 21%);
  --color-white: hsl(0, 0%, 100%);
  ...
 }
 ```
 It means that we pretty much need to copy-pasta the style file to the tailwind config, one by one ? 😖

**Comment by solidevolution** [comment]
This should work because single source of truth are the css variables in :root

**Comment by mokone91** [comment]
but how can i connect my 'tokens.css' with theme-viewer without parsing it to replacements?

**Comment by 2manoj1** [comment]
Have a look, How I did https://github.com/2manoj1/tailwind-default-config-viewer/blob/736b892120c919dbf4a9ed2a2115c9e4224ec510/tailwind.config.js#L5

https://github.com/2manoj1/tailwind-default-config-viewer/blob/main/utils/convert.js
