### ISSUE TITLE
tailwind config prefix duplicates dashes in CSS class names

### ISSUE THREAD

**Issue by alesso-x** [rogden/tailwind-config-viewer#14]
Using the prefix from the tailwind [docs](https://tailwindcss.com/docs/configuration#prefix) `tw-` produces classes with extra dashes. Instead of `tw-bg-black`, it becomes `tw--bg-black`.
<img width="1071" alt="Screen Shot 2020-10-13 at 10 40 40 PM" src="https://user-images.githubusercontent.com/8059120/95938072-1d777680-0da7-11eb-9d1a-78100e24c729.png">

I think the fix is to just check if the prefix ends with a dash and trim it [here](https://github.com/rogden/tailwind-config-viewer/blob/bc4956737c51a8521d1e6a2462f850c9f1dd6a63/src/components/Canvas/Canvas.vue#L86).

**Comment by rogden** [comment]
@alesso-x Thanks for reporting! Given the prefix can contain any valid CSS selector character, I ended up concatenating the prefix directly with the Tailwind class name without any additional logic to add/strip/replace characters.
