### ISSUE TITLE
Support for editing config from the viewer

### ISSUE THREAD

**Issue by theevilhead** [rogden/tailwind-config-viewer#20]
Hey @rogden,
Nice work btw, really helpful project.
What do you think of this: Adding support to edit the config from the viewer itself, as it will be really easy for users to do this and visualize.

**Comment by rogden** [comment]
Hey @theevilhead ! Thanks for the feedback and I'm glad you find the viewer helpful!

I've thought about this in the past, but it doesn't seem like the added complexity would be worth it. Often times, tailwind config files can be more complicated than simple JSON, especially in TW 2.0 where users may import different color pallets, require plugins etc.
