### ISSUE TITLE
Feature request: moving custom colors and styles ahead of Tailwind's built-in stuff, or giving them their own links in the sidebar

### ISSUE THREAD

**Issue by bseigel** [rogden/tailwind-config-viewer#21]
Hello,

This is super helpful, I appreciate you taking the time to build it. I found my way here via Craft Link List.

May I recommend an enhancement: either placing custom colors and styles ahead of Tailwind's built-in stuff, or creating links in the sidebar that jump right to one's customizations. It's the custom stuff that can be harder to remember than the built-in stuff.

**Comment by rogden** [comment]
Glad you are finding it helpful! Thanks for the feedback. This can be easily achieved by including tailwind colors after your custom colors instead of extending the tailwind colors:

```js
const { colors } = require('tailwindcss/defaultTheme')

module.exports = {
  theme: {
    colors: {
       'my-custom-color': '#FF0000',
       ...colors
    }
  }
}
```
