### ISSUE TITLE
[Feature Request] Add px equivalent to all rem values

### ISSUE THREAD

**Issue by ivandokov** [rogden/tailwind-config-viewer#23]
Congratulations for the great tool! 
Infact I started building the **exact same tool** some time ago but couldn't find the time to finish it so I will share some of my ideas to you and maybe you can incorporate them here. 

The main motivations for me for this tool are two: 
- preview your config with most generated classes as often the config changes quite drastically compared to the default due to design requirements
- be able to export the changed config and send it to designers for further design work so they know what we already have and not change it when they can reuse existing elements (or send the default config to designers for their reference while creating the design)

What I see here missing from my vision (ofcourse you can disagree) is to display all values which are in `rem` with pixes too. For example `p-4` is `1rem`. It will be really good to add `16px` next to the rem value so when you are working on a design frontend you can see quite fast the class you need. Obviously you memorise the common classes/sizes but sometimes the larger ones are hard to memorise as you don't use them often. 

Adding this to the tool will require a way to change the base font size for the rem->px calculation as it can be replaced in the frontend so adding an option such as `--base-font-size=16` will be required.

**Comment by rogden** [comment]
Thanks for the feedback and great idea! The thought definitely crossed my mind as I've used the tool more and more. I'll be adding this feature soon. I'll add a config prop to override the base size if needed:

```js
module.exports = {
  theme: {
    // ...your Tailwind theme config
    configViewer: {
      baseFontSize: 16 // 16 will be the default
    }
  }
}
```

**Comment by rogden** [comment]
Added in [v1.5.0](https://github.com/rogden/tailwind-config-viewer/releases/tag/v1.5.0)
