### ISSUE TITLE
[Feature Request] Multilingual support or config of example sentences

### ISSUE THREAD

**Issue by jalemy** [rogden/tailwind-config-viewer#24]
Thank you for great tool.

By the way, I have a question.
Do you have any plans to support multiple languages or read example sentences from the settings?

I'm software engineer in japan.
Japanese designer I work with told me that would like to check with japanese example sentences.

I'm sorry for my poor English, but I would appreciate if if you could comment.
I would like to cooperate by issuing a Pull Request if possible.

**Comment by rogden** [comment]
Hi @jalemy ! Thank you for the feedback and I am glad you are getting value from the tool!

Adding support for changing out the example sentence used for the font sections is a great idea. I think the following would do the trick:

1. Add a new config setting for the sentence:
```js
module.exports = {
  theme: {
    configViewer: {
      typographyExample: 'Your example sentence'
    }
  }
}
```

2. Each component in `src/components/Canvas/Sections` is passed the entire config if you add it as a prop. You can add the config prop it to the various font sections and output the example sentence from it if set. If it isn't set, output the default.

This should be a quick change. I'm happy to make it but if you'd like to contribute via a PR that would be great. Let me know.

**Comment by jalemy** [comment]
Thank you for advice<3

I will issue a pull request soon.

**Comment by jalemy** [comment]
@rogden 
I don't seem to have much write permission to this repository, and I can't create a pull request.
Can you please give me write permission?

**Comment by rogden** [comment]
@jalemy You should be able to create a fork and submit a PR from the fork.

**Comment by jalemy** [comment]
@rogden Thank you so much!
Sorry for the delay in submitting a pull request.

**Comment by rogden** [comment]
No worries @jalemy! Thanks for the PR. It looks good overall. I'll be make a few small changes. Notably moving the default value into a defaultOptions.js file to prevent us needing to duplicate the default string a few times. I need to do something similar for #23 to set a base font size for rem to px conversions.

**Comment by jalemy** [comment]
Thank you for your support<3

> defaultOptions.js

I see. that's helpful.

**Comment by rogden** [comment]
Added in [v1.5.0](https://github.com/rogden/tailwind-config-viewer/releases/tag/v1.5.0)
