### ISSUE TITLE
color contrast is not sufficient for accessibility

### ISSUE THREAD

**Issue by olets** [rogden/tailwind-config-viewer#35]
Much of the viewer's theme —notably nav links, section blocks, and values—  does not pass [WCAG color contrast requirements](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html). It'd be great to improve the color contrast to make this wonderful tool usable by more people.

**Comment by rogden** [comment]
@olets Thanks a ton for the feedback and contributions! I'll look at each in hopes of merging in this week. Much appreciated! 👍
