### ISSUE TITLE
The Background Image config isn't shown

### ISSUE THREAD

**Issue by dspacejs** [rogden/tailwind-config-viewer#42]
This [utility](https://tailwindcss.com/docs/background-image#background-images) is included in Tailwind, but it's not showing.

I've tried adding my own custom config, like this:

```js
module.exports = {
  theme: {
    extend: {
      backgroundImage: () => ({
        "dark-waves": "url('...')",
      }),
    },
  },
};
```

And this isn't showing either, but it does show in the app I'm building. I've tried changing the config to an object instead of a function, too, but this didn't work.

**Comment by rogden** [comment]
Hey @dspacejs! Currently background image utilities aren't supported in the config viewer. Knowing there are a lot of other utilities available in Tailwind, I'm trying to keep the config viewer focused on the most used/referenced utilities that users tend to customize (colors, text size, spacing etc) vs covering all available utilities. 

I'm looking into the possibility of allowing the config viewer to be extended by users with their own custom sections in the future.

**Comment by dspacejs** [comment]
@rogden hey, I disagree with this. The plugin should be updated with new utilities, as it's specifically made for Tailwind. 

Otherwise there's no way to test them in an isolated environment, and I'd have to use something like Storybook and this to achieve the same purpose, instead of having it all in one place.

Additionally, users shouldn't have to write custom sections for utilities that are standard in Tailwind. That should be included by default.

**Comment by ryanaltvater** [comment]
Glad I found this. I agree with @dspacejs here. I'm setting up a "styleguide"-like reference for my team. We're adopting Tailwind and I came across this as a fantastic solution, except it falls short by only displaying select utilities and now I have no way of testing/displaying the other utilities. Currently, I'm using this tool but I may need to look into something else if this is going to remain out-of-scope.

**Comment by ryanaltvater** [comment]
@dspacejs Do you have an example of yours somewhere (code + Storybook visual)? Would love to check it out. I need to get something like this set up for my team. We are launching our new Tailwind-based repo soon and the developers consuming the utilities could really use a reference. Thanks!
