### ISSUE TITLE
Disabling corePlugins in Tailwind config still shows classes in Viewer

### ISSUE THREAD

**Issue by ryan-ludwig** [rogden/tailwind-config-viewer#44]
When [disabling corePlugins ](https://tailwindcss.com/docs/configuration#core-plugins)in the config, which prevents Tailwind from generating those classes, the classes still show up in the config.
E.g.,
```
// tailwind.config.js
module.exports = {
	corePlugins: {
		boxShadow: false,
	},
	...
}
```
will still show the "Shadows" section in the config viewer and classes which aren't really available.

**Comment by ryanaltvater** [comment]
@rogden I'm still seeing this issue with v3.1.8 of Tailwind. Currently, I have this...

```
    corePlugins: {
        opacity: false,
    },
```

...and the "Opacity" section is still displaying, with the default opacity classes.
