### ISSUE TITLE
Ship esm version

### ISSUE THREAD

**Issue by tobiasdiez** [rogden/tailwind-config-viewer#49]
Currently, in the distributed/published version only commonjs is used. It would be nice if they would be also published as esm. This is needed for nuxt3/bridge, see https://github.com/nuxt-community/tailwindcss-module/issues/390 and https://v3.nuxtjs.org/concepts/esm#library-author-guide.

**Comment by rogden** [comment]
Thanks for the report. I'll need to dig into how to best do this. Might have to create a v2 and force node 12 instead of >=8. From my quick research it seems it can be quite a pain to manage both a cjs and esm version of a library.

**Comment by tobiasdiez** [comment]
Thanks for looking into this. Maintaining cjs + esm is indeed sadly not easy. The nuxt team developed https://github.com/unjs/unbuild that aims to help with this (I have no experience with this tool, but maybe its helpful).

**Comment by rogden** [comment]
As a quick fix so you can continue to use the viewer...you can turn it off in the Tailwind Nuxt Module config and then use it directly via `npx tailwind-config-viewer` assuming you have created a tailwind.config.js file in your Nuxt project root.

**Comment by ineshbose** [comment]
@rogden would you be accepting PRs for updating the project to newer solutions (like updating Vue 2 to Nuxt SSG, and unjs/h3, etc)? I've been keen for a while but would need to take time and effort on this; let me know and hopefully we can communicate over Discord (@ Orbviox) or somewhere suitable.

**Comment by bkjohnson** [comment]
@rogden would you accept PR(s) to make this compatible with [ESM tailwind configs](https://tailwindcss.com/docs/configuration#using-esm-or-type-script)? I'd be willing to help with that. Additionally, Node 18 is the lowest node version that isn't end of life, so a v2 release could include dropping unsupported node versions as well as a move to ESM compatibility.

**Comment by rogden** [comment]
@bkjohnson Absolutely!

**Comment by bkjohnson** [comment]
@rogden I opened #91 as a first step. I'm not a vue expert, but I'm assuming that being on the latest vue that uses vite will make it easier to ship a version with esm compatibility.

**Comment by rogden** [comment]
ESM support added in v2. Closing this out for now.

**Comment by ineshbose** [comment]
If I'm not wrong, this issue is more about the library moving to ESM syntax internally so possibly the surrounding ecosystem can also take advantage and benefit from it?

**Comment by tobiasdiez** [comment]
Supporting esm config files is nice, but I've opened this issue indeed with the wish to have a esm-version of the whole config-viewer package.

Could you please reopen the issue @rogden?

**Comment by ineshbose** [comment]
> Supporting esm config files is nice, but I've opened this issue indeed with the wish to have a esm-version of the whole config-viewer package.

#92 seems to be fresher issue
