### ISSUE TITLE
When fontWeights are defined the class names and values are not shown

### ISSUE THREAD

**Issue by JoA-MoS** [rogden/tailwind-config-viewer#67]
When defining custom font weights the class names and values are not shown

![image](https://user-images.githubusercontent.com/5566979/183774418-08978b5c-4d8f-4b20-aa04-bdc4dbcc21cc.png)

repro steps:
1. create new tailwinds library
2. update font weight property with something like
```
fontWeight: {
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
};
```
3. run config viewer

**Comment by hacknug** [comment]
@JoA-MoS just opened a PR with a fix for this.

@rogden left some comments on the PR with an alternative fix and some potential issues I see with the way this currently works. Not familiar with the codebase so I'm not sure those would 100% apply or not.
