### ISSUE TITLE
When exporting to static html: Access to fetch from origin 'null' has been blocked by CORS policy

### ISSUE THREAD

**Issue by autonomobil** [rogden/tailwind-config-viewer#85]
Probably connected to https://github.com/rogden/tailwind-config-viewer/issues/62
![image](https://user-images.githubusercontent.com/31781343/233631679-8b4ff2b2-2f97-4e13-8932-75b5e4441f65.png)

**Comment by rogden** [comment]
@autonomobil Are you opening the index.html file directly from your filesystem? If that is the case you will always receive this error. If you want to run the exported site locally you will need to run it via a local server. There are a few node packages that can server a local directory or if you have php installed you can `cd` into the exported directory and run `php -S localhost:3001` (or whatever port you want) and it will server the index.html file correctly without the CORS issue.
