### ISSUE TITLE
Outdated koa router

### ISSUE THREAD

**Issue by GalacticHypernova** [rogden/tailwind-config-viewer#90]
warning @nuxtjs/tailwindcss > tailwind-config-viewer > @koa/router@9.4.0: **IMPORTANT 10x+ PERFORMANCE UPGRADE**: Please upgrade to v12.0.1+ as we have fixed an issue with debuglog causing 10x slower router benchmark performance, see https://github.com/koajs/router/pull/173

**Comment by metkm** [comment]
Having the same issue. I guess this was the reason why my dev server become so slow?

**Comment by GalacticHypernova** [comment]
Most likely..

**Comment by maximepvrt** [comment]
@rogden 🙏

**Comment by NBZ-Vasil** [comment]
Same thing here, experienced a sharp performance drop on my dev machine after installing @nuxtjs/tailwindcss.

**Comment by metkm** [comment]
This is related to https://github.com/nuxt/ui/issues/845

**Comment by rogden** [comment]
Updated in https://github.com/rogden/tailwind-config-viewer/releases/tag/v1.7.3

**Comment by GalacticHypernova** [comment]
Thank you very much!

**Comment by NBZ-Vasil** [comment]
Thanks for the quick resolution
